require('plugs.lualine-conf')
require('plugs.comment-conf')
-- require('plugs.null-ls-conf')
require('plugs.formatter-conf')
require('plugs.nvim-tree-conf')
require('plugs.nvim-treesitter-conf')
require('plugs.telescope-conf')
require('plugs.nvim-autopairs-conf')
require('plugs.colorscheme-conf')
