local vimOpt = vim.opt

vimOpt.hidden = true
vimOpt.smartindent = true
vimOpt.expandtab = true
vimOpt.showmatch = true
vimOpt.secure = true
vimOpt.smartcase = true
vimOpt.relativenumber = true
vimOpt.wrap = false
vimOpt.backup = false
vimOpt.writebackup = false
vimOpt.lazyredraw = true
vimOpt.tabstop = 2
vimOpt.shiftwidth = 2
vimOpt.softtabstop = 2
vimOpt.laststatus = 2
vimOpt.encoding = 'utf-8'
vimOpt.completeopt = { 'menu' , 'menuone' , 'noselect' }
vimOpt.shortmess = vim.opt.shortmess + 'c'
vimOpt.background = 'dark'
