vim.opt.hidden = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.showmatch = true
vim.opt.secure = true
vim.opt.smartcase = true
vim.opt.relativenumber = true
vim.opt.wrap = false
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.lazyredraw = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.laststatus = 2
vim.opt.encoding = 'utf-8'
vim.opt.completeopt = { 'menu' , 'menuone' , 'noselect' }
vim.opt.shortmess = vim.opt.shortmess + 'c'
vim.opt.background = 'dark'
