require('settings.001-preload')
require('settings.002-plugins')
require('settings.003-keymaps')
require('settings.004-lsps')

require('settings.plug-confs.lualine-conf')
require('settings.plug-confs.comment-conf')
require('settings.plug-confs.null-ls-conf')
require('settings.plug-confs.nvim-tree-conf')
require('settings.plug-confs.nvim-treesitter-conf')
require('settings.plug-confs.telescope-conf')
require('settings.plug-confs.colorscheme-conf')
